/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package userArtifact;

import java.util.Objects;
import java.util.UUID;

public class User {

    private UUID UserID;
    private String FName;
    private String LName;
    private String email;

    public UUID getUserID() {
        return UserID;
    }

    public void setUserID(UUID userID) {
        UserID = userID;
    }

    public String getFName() {
        return FName;
    }

    public void setFName(String FName) {
        this.FName = FName;
    }

    public String getLName() {
        return LName;
    }

    public void setLName(String LName) {
        this.LName = LName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return UserID.equals(user.UserID);
    }

    @Override
    public int hashCode() {
        return Objects.hash(UserID);
    }

    @Override
    public String toString() {
        return "User{" +
                "UserID=" + UserID +
                ", FName='" + FName + '\'' +
                ", LName='" + LName + '\'' +
                ", email='" + email + '\'' +
                '}';
    }
}
